//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPp_1_22_Yuritsyna
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectRate
    {
        public int DefectRateID { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> ProductionID { get; set; }
        public Nullable<decimal> DefectPercentage { get; set; }
        public string Reason { get; set; }
    
        public virtual Production Production { get; set; }
    }
}
