//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPp_1_22_Yuritsyna
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Master_polEntities : DbContext
    {
        public Master_polEntities()
            : base("name=Master_polEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DefectRate> DefectRate { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
