//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPp_1_22_Yuritsyna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Production()
        {
            this.DefectRate = new HashSet<DefectRate>();
        }
    
        public int ProductionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string ProductType { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Article { get; set; }
        public Nullable<decimal> PricePartner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectRate> DefectRate { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
